name: Automated tests

on:
  push

jobs:
  download-history: 
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/oksanasergienko/run-tests-demo/actions/artifacts?name=allure-results" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])")
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/oksanasergienko/run-tests-demo/actions/artifacts/$ARTIFACT_ID/zip 
          -o artifacts.zip
      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - name: Store allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1


  test:
    runs-on: ubuntu-latest
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Run tests
        run: pytest --alluredir=allure-results
      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1


  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Download and setup Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz
          tar -zxvf allure-2.32.0.tgz
          sudo mv allure-2.32.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4 
      - run: allure generate -c allure-results -o _site
      - name: Store generated reports
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    permissions: 
      id-token: write
      pages: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9


        